#= require ./store
#= require_tree ./core/initializers
#= require_tree ./core/models
#= require_tree ./models
#= require_tree ./core/mixins
#= require_tree ./core/controllers
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./helpers
#= require_tree ./core/components
#= require_tree ./templates
#= require_tree ./routes
#= require ./router
#= require ./core/authenticator
#= require_self
